### ISSUE TITLE
binder not working

### ISSUE THREAD

**Issue by jgunstone** [trungleduc/ipyflex#35]
![image](https://user-images.githubusercontent.com/21370980/152840086-17a652d1-315c-47d8-bba4-b23129430ad1.png)

**Comment by trungleduc** [comment]
Hi @jgunstone, it seems to be an issue from `binder` side, it works well now for me.

![binder-ipyflex](https://user-images.githubusercontent.com/4451292/152871464-2789eec6-fb33-406b-9eab-14e2739f6d86.png)

**Comment by jgunstone** [comment]
working great for me now - 
this package looks awesome!
