### ISSUE TITLE
Ipyflex with Jupyterlite

### ISSUE THREAD

**Issue by DougRzz** [trungleduc/ipyflex#40]
Hi,  Ipyflex is a great library. Thanks for sharing!

I couldn't get Ipyflex to display in Jupyterlite.  If possible, please could you show an example of Ipyflex working in Jupyterlite. 

Here is the sample code I used that didn't work.
```python
import micropip
await micropip.install("ipyflex")
import ipyflex

ipyflex.FlexLayout(
    header={"title": "Test", "style": {"backgroundColor": "rgb(53 53 53)"}}, # , "buttons":["export","import"]
)
```
The widget doesn't display. I just get the "Loading widget..." text under the cell.

**Comment by trungleduc** [comment]
Hi @DougRzz, you can check out https://github.com/trungleduc/ipyflex-lite for a demo of `ipyflex` + `jupyterlite`. 
Basically, you need to install the frontend part of `ipyflex` while building your `jupyterlite` site.

**Comment by DougRzz** [comment]
@trungleduc That is awesome. Jupyterlite is just incredible technology. 

I think I forget to do a force refresh after I put ipyflex in the requirements. Thats why I was getting a Loading Widgets... 

To load a template into ipyflex, I got this to work:
```python
import json
import pyodide
import ipyflex

ipyflex.FlexLayout(
    style={"height": height}, #
    header={"title": "Experimental DASHBOAD", "style": {"backgroundColor": "rgb(53 53 53)"}},
    template_json=json.loads(pyodide.open_url("https://raw.githubusercontent.com/therestofyourURL/NC.json").getvalue()),
)
```
