### ISSUE TITLE
configuring the layout / flex functionality? 

### ISSUE THREAD

**Issue by jgunstone** [trungleduc/ipyflex#41]
hi there, 

excited to use this! 

I'm considering a use case for ipyflex as a UI for creating an A4 format output pdf report. 

To do so i'd like to use the widget factory, allowing users to add items to the report, and specify that items must be vertically stacked, i.e.: 
![image](https://user-images.githubusercontent.com/21370980/172806406-677b6e0f-551e-469e-93db-7a7aaee2ff0a.png)

ideally the user would be able to drag the boxes up and down to change order but wouldn't be able to do anything else... 

is this possible? 

many thanks

**Comment by trungleduc** [comment]
Hello, for now you can either lock the interface or allow all modifications. You can not allow users to add widget but limit the drag/drop operators
