### ISSUE TITLE
Tab bar hides upon FlexLayout.load_template

### ISSUE THREAD

**Issue by margrietpalm** [trungleduc/ipyflex#51]
We use ipyflex to let our users build their own dashboard. This works great, but at some moments the tab bar, with the '+' button, becomes hidden without any user interaction requesting this behavior. One of such moment is upon `FlexLayout.load_template`.

Unfortunately, I cannot share the full code we are using. But if needed I can try to create a MWE. Note that just disabling the whole 'hide tab bar' feature would already be a big help.

**Comment by margrietpalm** [comment]
I've been trying to reproduce the issue with stock ipyflex, but it only seem to happen in the slightly modified version we're using. There are no errors being raised whenever the issue occurs. Unfortunately, my knowledge of javascript and typescript is too limited to track down how the tab bar is managed.

**Comment by trungleduc** [comment]
Are you on the latest version? I've fixed a bug related to the tab bar recently #34
