### ISSUE TITLE
Compare with Lumino?

### ISSUE THREAD

**Issue by deeplook** [trungleduc/ipyflex#8]
Very nice! Have you considered using https://github.com/jupyterlab/lumino, too?

**Comment by trungleduc** [comment]
Hi @deeplook, it's surely feasible with lumino. It's just my personal choice to save time since I'm more familiar with the [FlexLayout](https://github.com/caplin/FlexLayout) library. In fact, except for the layout manager, I reused all the UI components and CSS  from `jupyterlab`
